### ISSUE TITLE
Issue with Semantic relatedness measure

### ISSUE THREAD

**Issue by iknoorjobs** [dscarvalho/easyesa#1]
Case 1.
Semantic relatedness measure between term1 ('computing') and term2 ('sensor')
http://localhost:8800/esaservice?task=esa&term1=computing&term2=sensor
This gives output : "0.0054620505"

Case 2.
But if I separately invoke concept vector for each term1 ('computing') and term2 ('sensor') using
vec1 = http://localhost:8800/esaservice?task=vector&source=computing&limit=50
vec2 = http://localhost:8800/esaservice?task=vector&source=sensor&limit=50
where vec1 and vec2 are extracted vectors from JSON.

Now when I take the cosine similarity between them, then output is 0.99728391

Why is this difference between Case 1. and Case 2. when both are using cosine similarity?

Please help.
Thanks

**Comment by dscarvalho** [comment]
Hi Iknoor,

Have you tried without truncating the vector at 50 dimensions?
In this case, The vectors may be close at the first values, but diverge further on.


Best regards,
Danilo S. Carvalho.

**Comment by iknoorjobs** [comment]
Yes, I have tried. The maximum available concept vector for the computing is 980.
Still, it's giving similar results (=0.99517)

There is a huge difference between 0.99517 and 0.005462.
Please help.
Thanks

**Comment by iknoorjobs** [comment]
Hey, any idea what's the issue?

**Comment by dscarvalho** [comment]
I started looking into it, but got into 2 very busy weeks.
I will update here as soon as I find the problem.

**Comment by iknoorjobs** [comment]
Cool, thanks.

**Comment by dscarvalho** [comment]
I've just checked the code and tested the output vectors, but could not find significant difference between the relatedness calculated by the service with task=esa and the one calculated independently from the vectors obtained with task=vector.
Can you show me the code that produced your results?

I used the attached python program to check the relatedness. It calculates the cosine of the output vectors. The small difference between the result of this program and the task=esa result is due to float truncation.
You can run it like: 
python3 test_cosinesim.py computing sensor



[test_cosinesim.py.gz](https://github.com/dscarvalho/easyesa/files/3184475/test_cosinesim.py.gz)
